version: 2.1
orbs:
  ms-teams: cloudradar-monitoring/ms-teams@1.0.0
jobs:
  build:
    executor: docker
    steps:
      - checkout
      - run: command/to/run/your/tests
      - ms-teams/report:
          only_on_fail: true
          webhook_url: https://usthaan715.webhook.office.com/webhookb2/216c2a55-0aa5-4121-b3c2-df0afe704437@cdfad6cb-99df-4451-ac6b-8cb2eca5058c/IncomingWebhook/54dae55e2c9d4729819d10e95cfe152a/039b64f3-af48-4160-bc30-f202ba06c0b1